# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Doris/Desktop/FPGA/Lab2_hw_BD/Lab2_hw_BD.srcs/sources_1/bd/HW2_1/ip/HW2_1_RGB_LED_0_0/HW2_1_RGB_LED_0_0.xci
# IP: The module: 'HW2_1_RGB_LED_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Doris/Desktop/FPGA/Lab2_hw_BD/Lab2_hw_BD.srcs/sources_1/bd/HW2_1/ip/HW2_1_RGB_LED_0_0/src/RGB_LED_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'HW2_1_RGB_LED_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Doris/Desktop/FPGA/Lab2_hw_BD/Lab2_hw_BD.srcs/sources_1/bd/HW2_1/ip/HW2_1_RGB_LED_0_0/HW2_1_RGB_LED_0_0.xci
# IP: The module: 'HW2_1_RGB_LED_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Doris/Desktop/FPGA/Lab2_hw_BD/Lab2_hw_BD.srcs/sources_1/bd/HW2_1/ip/HW2_1_RGB_LED_0_0/src/RGB_LED_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'HW2_1_RGB_LED_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
