# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Doris/Desktop/FPGA/2019_FPGA_Design/Lab02/Lab2-1/xdc/pynq-z2_v1.0.xdc

# Block Designs: bd/HW2_1/HW2_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HW2_1 || ORIG_REF_NAME==HW2_1} -quiet] -quiet

# IP: bd/HW2_1/ip/HW2_1_RGB_LED_0_0/HW2_1_RGB_LED_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HW2_1_RGB_LED_0_0 || ORIG_REF_NAME==HW2_1_RGB_LED_0_0} -quiet] -quiet

# IP: bd/HW2_1/ip/HW2_1_PWM_Decoder_0_0/HW2_1_PWM_Decoder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HW2_1_PWM_Decoder_0_0 || ORIG_REF_NAME==HW2_1_PWM_Decoder_0_0} -quiet] -quiet

# XDC: bd/HW2_1/HW2_1_ooc.xdc
